edition = "2023";

package ULocalMagnitudeServiceAPI.V1.Magnitude;

import "uLocalMagnitudeServiceAPI/v1/magnitude/stream_identifier.proto";

/**
 * Defines an observed (peak to peak) amplitude.
 */
message Amplitude {
   /// The units on the measurement.
   enum Units {
       UNKNOWN = 0,     /// The units are unknown and an error will be generated.
       MILLIMETERS = 1, /// The amplitude was measured in units of millimeters (pretty common).
       CENTIMETERS = 2, /// The amplitude was measured in units of centimeters (sometimes happens).
       METERS = 3       /// The amplitdue was measured in units of meters (uncommon).
   }
   /// The stream identifier on which the amplitude was made.
   StreamIdentifier stream_identifier = 1;
   /// The observed amplitude.  This must be positive.
   double value = 2;
   /// The units of the amplitude.  If unknown then this will result in an error.
   Units units = 3;
}
