edition = "2023";

package ULocalMagnitudeServiceAPI.V1.Magnitude;

/**
 * This distance corrections at the given source-receiver distances.
 */
message DistanceCorrectionsResponse {
  message DistanceCorrection {
     /// The distance in meters.
     double distance = 1;
     /// The correction.  This value is directly added to the station
     /// magnitude - i.e., this is the C_d in the relation:
     ///    Station Magnitude = log10(A) + C_d + C_s
     double correction = 2;
  };
  /// The identifier corresponding to the response.
  string identifier = 1 [default = ""];
  /// The distance corrections.
  repeated double distance_corrections = 2;
}
