edition = "2023";
import "google/protobuf/timestamp.proto";

package ULocalMagnitudeServiceAPI.V1.Magnitude;

/*
 * The event origin (hypocenter and time).
 */
message Origin {
   /// The event latitude in degrees.  This must be in the range [-90, 90].
   /// This increases positive north.
   double latitude = 1;
   /// The event longitude in degrees.  This increases positive east.
   double longitude = 2;
   /// The event depth in meters.  This increases positive down.  It
   /// must be in the range [-8600, 900000].
   double depth = 3;
   /// The origin time.
   google.protobuf.Timestamp time = 4;
}
