edition = "2023";

package ULocalMagnitudeServiceAPI.V1.Magnitude;

import "uLocalMagnitudeServiceAPI/v1/magnitude/amplitude.proto";
import "uLocalMagnitudeServiceAPI/v1/magnitude/station_location.proto";

/**
 * Defines a (peak-to-peak) amplitude measurement made at a station.
 * At UUSS station local magnitudes are computed by averaging amplitudes
 * observed on a pair of non-vertical channels at a station.
 */
message StationAmplitudeMeasurement {
   /// The amplitude measured on the first channel (e.g., HHE).
   Amplitude amplitude_stream_1 = 1;
   /// The amplitude measured on the second channel (e.g., HHN).
   Amplitude amplitude_stream_2 = 2;
   /// The station location in the WGS84 system.
   StationLocation station_location = 3;
}   
