edition = "2023";

package ULocalMagnitudeServiceAPI.V1.Magnitude;

import "uLocalMagnitudeServiceAPI/v1/magnitude/station_identifier.proto";

/**
 * This station corrections for the given stations.
 */
message StationCorrectionsResponse {
  message StationCorrection {
     /// The station identifier.
     StationIdentifier station_identifier = 1;
     /// The vaue of the correction.  This value is directly added to the station
     /// magnitude - i.e., this is the C_s in the relation:
     ///    Station Magnitude = log10(A) + C_d + C_s
     double value = 2 [default = 0];
     /// A flag indicating the corrections exists.
     bool exists = 3;
  };  
  /// The identifier corresponding to the response.
  string identifier = 1 [default = ""];
  /// The station corrections.
  repeated double station_corrections = 2;
}

