edition = "2023";

package ULocalMagnitudeServiceAPI.V1.Magnitude;

import "uLocalMagnitudeServiceAPI/v1/magnitude/amplitude.proto";

/*
 * The station magnitude corresonding to the input measurements.
 */
message StationMagnitude {
   /// The first amplitude measurement used in the station magnitude calculation.
   Amplitude amplitude_1 = 1;
   /// The second amplitude measurement used in the station magnitude calculation.
   Amplitude amplitude_2 = 2;
   /// The station magnitude.  To compute the uncorrected magnitude use:
   ///   uncorrected = magnitude - station_correction - distance_correction
   double magnitude = 3;
   /// The station correction that was added to the station magnitude.
   double station_correction = 4;
   /// The distance correction that was added to station magnitude.
   double distance_correction = 5;
   /// Indicates a station correction existed in configuration and was
   /// applied.  
   bool used_station_correction = 6;
} 
