edition = "2023";

package ULocalMagnitudeServiceAPI.V1.Magnitude;

import "uLocalMagnitudeServiceAPI/v1/magnitude/hypocenter.proto";
import "uLocalMagnitudeServiceAPI/v1/magnitude/station_amplitude_measurement.proto";

/**
 * Requests that station magnitudes be computed from the given amplitude
 * measurements.
 */
message StationMagnitudesFromAmplitudesRequest {
   /// A request identifier.
   string identifier = 1 [default = ""];
   /// A list of amplitudes measured on different stations.
   repeated StationAmplitudeMeasurement station_amplitude_measurements = 2;
   /// The event location.
   Hypocenter hypocenter = 3;
}
